platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'OCBase' do
  
    pod 'MJExtension', '~> 3.0.15.1'
    pod 'pop', '~> 1.0.10'
    pod 'MJRefresh', '~> 3.1.15.7'
    pod 'SDWebImage', '~> 5.0.0-beta3'
    pod 'IQKeyboardManager', '~> 6.2.0'
    pod 'DateTools', '~> 2.0.0'
    pod 'MBProgressHUD'
    pod 'DZNEmptyDataSet'
    pod 'AFNetworking'
    pod 'FDStackView'
    pod "CYLTabBarController", "~>1.11.0"
    # 全屏返回框架
    # pod 'FDFullscreenPopGesture', '1.1'
    # pod 'WRNavigationBar'
    # 最近不维护了
    pod 'Masonry'
    # pod 'SDAutoLayout', '~> 2.1.3'
    # OC的稳定版本是2.5
    # pod 'ReactiveCocoa', '~> 2.5'
    # pod 'HYBImageCliped'
    # pod 'YYText', '~> 1.0.7'
    #pod 'SDCycleScrollView', '~> 1.75'

    # pod 'LBXScan'
    # pod 'INTULocationManager'
    # pod 'CocoaSecurity'

    # 数据库
    # pod 'Realm'
    # pod 'FMDB', '~> 2.6.2'
    # 不需要写sql语句，通过model操作数据库
    # pod 'YIIFMDB'

    # 分页查看器
    # pod 'TYPagerController'
    # pod 'TZImagePickerController'
    # 已经很久没有维护了
    # pod 'LPPhotoViewer', '~> 0.0.7’
    # 角标
    # pod 'JSBadgeView'

    # 弹窗框架
    # pod 'LEEAlert'
    # 换肤框架
    # pod 'LEETheme'

    # 如何在列表中优雅的嵌入广告
    # pod 'IMYAOPTableView'

    # 面向切面编程
    pod 'Aspects'

    # 指纹校验：https://www.jianshu.com/p/4a0bec497ebd
    # iCloud开发：https://www.jianshu.com/p/33ebab1c2ee1
    # 登录成功后，重新请求网络：https://www.jianshu.com/p/6c5f711a0252
    # NullSafe: https://github.com/nicklockwood/NullSafe
    # TableView加载图片的优化方案：https://www.jianshu.com/p/328e503900d0
    # CollectionView加载图片优化方案: https://www.jianshu.com/p/32fe33caca3f
    # 好多叠在一起的button常见直播：https://www.jianshu.com/p/b1f715035adc

    # 动画相关：https://www.kancloud.cn/manual/ios/97759
    # 一句话实现转场动画：https://github.com/308823810/SS_AnimationTransition

end
