platform :ios, '8.0'
# use_frameworks! # 主要是swift使用
inhibit_all_warnings!

target 'OCBase' do
  
    pod 'MJExtension', '~> 3.0.15.1'
    pod 'pop', '~> 1.0.10'
    pod 'MJRefresh', '~> 3.1.15.7'
    pod 'SDWebImage', '~> 5.0.0-beta3'
    pod 'IQKeyboardManager', '~> 6.2.0'
    pod 'DateTools', '~> 2.0.0'
    pod 'MBProgressHUD'
    pod 'DZNEmptyDataSet'
    pod 'AFNetworking'
    pod 'UICKeyChainStore' # 钥匙链.
    pod 'NSData+MD5Digest' # MD5 验证.
    pod 'FDStackView'
    pod "CYLTabBarController", "~>1.11.0"
    # 微信平滑过渡的导航栏
    # pod 'HBDNavigationBar', '~> 1.4.4'
    # 导航控制器（可以全屏返回）
    # pod "RTRootNavigationController"
    # 分页查看器
    # pod 'TYPagerController'
    # pod 'VTMagic', '~> 1.2.4'
    # pod 'JXCategoryView'
    # pod 'SGPagingView', '~> 1.6.0'

    # 全屏返回框架
    # pod 'FDFullscreenPopGesture', '1.1'
    # pod 'WRNavigationBar'
    
    # 自动布局 最近不维护了
    pod 'Masonry'
    # pod 'SDAutoLayout', '~> 2.1.3'
    # pod 'PureLayout'
    # 基于frame布局，性能更高
    # pod 'MyLayout'
    
    # OC的稳定版本是2.5
    # pod 'ReactiveCocoa', '~> 2.5'
    # pod 'HYBImageCliped'
    # pod 'YYText', '~> 1.0.7'
    # pod 'SDCycleScrollView', '~> 1.75'
    
    # 导航栏弹窗
    # pod 'JDStatusBarNotification'
    
    # 内存占用检测
    # pod 'OOMDetector', '1.3'
    # 检测内容泄漏
    # pod 'MLeaksFinder', '~> 1.0.0'

    # 解压工具
    # pod 'SSZipArchive'

    # 防护框架
    # pod 'JJException', '~> 0.1.2'

    # 商店跳转评分
    # pod 'Appirater', '~> 2.3.1'

    # pod 'LBXScan'
    # 获取定位信息
    # pod 'INTULocationManager'
    # pod 'CocoaSecurity'

    # 数据库
    # pod 'Realm'
    # pod 'FMDB', '~> 2.6.2'
    # 不需要写sql语句，通过model操作数据库
    # pod 'YIIFMDB'
    pod 'WCDB', '~> 1.0.7.5'
    # XWDatabase

    # 图片选择器
    # pod 'TZImagePickerController'
    # pod 'HXPhotoPicker', '~> 2.2.3'
    # pod 'LBPhotoBrowser', '~> 2.2.2'

    # 已经很久没有维护了
    # pod 'LPPhotoViewer', '~> 0.0.7’
    # 角标
    # pod 'JSBadgeView'

    # 弹窗框架
    # pod 'LEEAlert'
    # 带动画的弹窗框架,内容view自定义
    # pod 'FFPopup'
    # 换肤框架
    # pod 'LEETheme'

    # 如何在列表中优雅的嵌入广告
    # pod 'IMYAOPTableView'

    # 面向切面编程
    pod 'Aspects'

    # 分类框架
    # pod 'JKCategories'

    # 边下边播的音频播放器
    # pod 'WTAudioPlayer', '~> 1.0.4'
    # SVGA文件播放
    # pod 'SVGAPlayer'

    # 文件解压缩
    # pod 'SSZipArchive'
    pod 'ZipArchive', '~> 1.4.0',:inhibit_warnings => true
    
    # 添加网络缓存框架
    pod 'PINCache', '~> 3.0.1-beta.7'
    pod 'YYCache', '~> 1.0.4'
    
    # 前台推送框架
    # pod 'EBBannerView', '~> 1.0.8'
    
    # 代码格式化
    # OBLint
    
    # 任务调度，为CPU减负 这个作者有几个好玩的仓库
    # pod 'YBTaskScheduler'
    
    # 阿里的携程库实现
    pod 'coobjc', '~> 1.0.1'
    
    # 融360  Face++人脸识别及身份证、银行卡扫描
    # https://www.jianshu.com/p/66a142505bc9
    
    # 嵌套滚动方案
    # https://juejin.im/post/5c7f4cb9e51d452bfa4d6fe5
    
    # appdelegate 模块化
    # https://juejin.im/post/5c7f8b34e51d454f8a0c5136

    # 指纹校验：https://www.jianshu.com/p/4a0bec497ebd
    # iCloud开发：https://www.jianshu.com/p/33ebab1c2ee1
    # 登录成功后，重新请求网络：https://www.jianshu.com/p/6c5f711a0252
    # NullSafe: https://github.com/nicklockwood/NullSafe
    # TableView加载图片的优化方案：https://www.jianshu.com/p/328e503900d0
    # CollectionView加载图片优化方案: https://www.jianshu.com/p/32fe33caca3f
    # 好多叠在一起的button常见直播：https://www.jianshu.com/p/b1f715035adc
    # 表格控件 https://github.com/sabersensen/ZSXChartDemo

    # 动画相关：https://www.kancloud.cn/manual/ios/97759
    # 一句话实现转场动画：https://github.com/308823810/SS_AnimationTransition
    # 好用动画： https://github.com/Abnerzj/ZJAnimationPopView
    # 转场动画： https://www.jianshu.com/p/ec08f43808aa
    # 弹窗动画： https://www.jianshu.com/p/6f87ba558279
    # 炫酷动画： https://github.com/Yalantis/StarWars.iOS
    # 物联网 SmartConfig 一键配网     GCDSocketManager 长连接
    # 国家/地区选择器 https://www.jianshu.com/p/48ca8cbe561b
    # app禁止截屏： https://www.jianshu.com/p/1823499b7499
    # 线程安全写文件：https://www.cnblogs.com/bomo/p/4668599.html
    # 很好的网络缓存方案： http://www.cocoachina.com/cms/wap.php?action=article&id=19954
    # 搭建日志系统： https://www.jianshu.com/p/0f889e75f387 pod 'CocoaLumberjack', '~> 3.4.2'
    # 图片jpg转png https://www.xunjiepdf.com/compress
    # 导入头文件 https://github.com/markohlebar/Import/releases
    # 使用Runtime找到图片的名字 http://www.cocoachina.com/ios/20181226/25965.html
    
    # 有意思的应用：
    # https://github.com/coderyi/Monkey/blob/master/README_Chinese.md
    # https://github.com/Coding/Coding-iPad/tree/master/CodingForiPad
    # https://github.com/Aufree/phphub-ios
    
    # json 浏览器插件：https://github.com/rfletcher/safari-json-formatter/downloads
    # 流量监测方案： http://zhoulingyu.com/2018/05/30/ios-network-traffic/
    # RAC实现MVVM Demo: http://zhoulingyu.com/2016/05/20/iOS——教你如何使用ReactiveCocoa和MVVM为代码解耦构建清爽APP/
    
    # app国际化 https://github.com/JmoVxia/CLDemo
    
    # 面试
    # 1.iOS 内存分配：http://www.cocoachina.com/ios/20190307/26495.html
    
    # 数据库迁移
    # https://blog.csdn.net/zhangyutangde/article/details/78339120
    
    # 单边设置阴影
    # https://github.com/YotrolZ/YCShadowView
    # 照片添加水印
    # https://www.jianshu.com/p/8d5ac876e4ff
    # IOKit获取电池电量: https://www.jianshu.com/p/bd9ebc815115
    # WKWebView崩溃记录——SIGSEGV(11): https://www.jianshu.com/p/b302e8a639aa
    # 原生嵌套RN: https://www.jianshu.com/p/13cbdbd1550f
    # iOS管理多个弹窗弹出-信号量应用：https://www.jianshu.com/p/8ebfd758a200
    # 仿美图定制：https://www.jianshu.com/p/f6ce3a5c8da8
    # iOS AOP简单实现日志打点[Aspects]： https://www.jianshu.com/p/3167fad8a328
    # Xcode控制台输出内容不全： https://www.jianshu.com/p/26c02014f9f2
    # 混淆垃圾代码：https://www.jianshu.com/p/b58b38d8bb8b
    # TableViewDataSource拆分：https://www.jianshu.com/p/5031c370a33a
    # iOS KVO安全移除所有观察者 防止重复添加或者删除监听：https://www.jianshu.com/p/98ff6dfa4802
    
end
